FROM docker.io/ubuntu:latest@sha256:513c074113a871b51a8d16ab445c88779d6452d937a164fb5cc479f32668a41d
ARG IMGPACK_FILTER=
COPY / /kernel-img-repository/${IMGPACK_FILTER}

LABEL org.opencontainers.image.source https://github.com/elastic/ebpf

CMD ["/bin/bash", "-c", "cp -r /kernel-img-repository/* /kernel-images/"]
