name: pahole-staging

on:
  schedule:
    - cron:  '0 18 * * *'


jobs:
  vmtest:
    runs-on: ubuntu-20.04
    name: Kernel LATEST + staging pahole
    env:
      STAGING: tmp.master
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/vmtest
        with:
          kernel: LATEST
          pahole: $STAGING
