on:
  workflow_call:

jobs:
  local-image-build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, aarch64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure System
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-user-static
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Test Container Image Formatting
        run: make test-format BUILD_CONTAINER_IMAGE=True ARCH=${{matrix.arch}}
      - name: Test Container Image Build
        run: make build BUILD_CONTAINER_IMAGE=True ARCH=${{matrix.arch}}
      - name: Test Packaging
        run: make package BUILD_CONTAINER_IMAGE=True ARCH=${{matrix.arch}}
