on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
        description: Architecture string, for example aarch64
      runner:
        required: true
        type: string
        description: The runner to execute the build on, for example ubuntu-latest

jobs:
  local-image-build:
    name: Container Image Build
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure System
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-user-static
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Test Container Image Formatting
        run: make test-format BUILD_CONTAINER_IMAGE=True ARCH=${{ inputs.architecture }}
      - name: Test Container Image Build
        run: make build BUILD_CONTAINER_IMAGE=True ARCH=${{ inputs.architecture }}
      - name: Test Packaging
        run: make package BUILD_CONTAINER_IMAGE=True ARCH=${{ inputs.architecture }}
